---
# Note this is not an exhaustive list of all configuration values
collectors:
  enabled: ad,cpu,cpu_info,cs,dhcp,dns,hyperv,logical_disk,logon,memory,mssql,net,os,service,smb,system,thermalzone,terminal_services,textfile
collector:
  service:
    services-where: Name='windows_exporter'
  scheduled_task:
    include: /Microsoft/.+
log:
  level: debug
scrape:
  timeout-margin: 0.5
telemetry:
  path: /metrics
  max-requests: 5
web:
  listen-address: ":9182"
